kind: Deployment
apiVersion: apps/v1
metadata:
  name: elastic-vectordb-chat
  namespace: elastic-vectordb-chat
  labels:
    app: elastic-vectordb-chat
    app.kubernetes.io/component: elastic-vectordb-chat
    app.kubernetes.io/instance: elastic-vectordb-chat
    app.kubernetes.io/name: elastic-vectordb-chat
    app.kubernetes.io/part-of: elastic-vectordb-chat-app
    app.openshift.io/runtime-namespace: elastic-vectordb-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-vectordb-chat
  template:
    metadata:
      labels:
        app: elastic-vectordb-chat
        deployment: elastic-vectordb-chat
    spec:
      containers:
        - name: elastic-vectordb-chat
          image: 'quay.io/jhurlocker/elastic-vectordb-chat'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8501
              protocol: TCP
          env:
            - name: MODEL_ENDPOINT
              value: 'https://mistral7b-podman-ai-lab-rag-project.apps.cluster-6f5sd.dynamic.redhatworkshops.io'
            - name: ELASTIC_URL
              value: 'https://172.31.251.93:9200'
            - name: ELASTIC_PASS
              value: '0OF95m0oadUMf189q56R2YQq'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: elastic-vectordb-chat
  namespace: elastic-vectordb-chat
  labels:
    app: elastic-vectordb-chat
    app.kubernetes.io/component: elastic-vectordb-chat
    app.kubernetes.io/instance: elastic-vectordb-chat
    app.kubernetes.io/name: elastic-vectordb-chat
    app.kubernetes.io/part-of: elastic-vectordb-chat-app
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8501-tcp
      protocol: TCP
      port: 8501
      targetPort: 8501
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: elastic-vectordb-chat
    deployment: elastic-vectordb-chat
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elastic-vectordb-chat
  namespace: elastic-vectordb-chat
  labels:
    app: elastic-vectordb-chat
    app.kubernetes.io/component: elastic-vectordb-chat
    app.kubernetes.io/instance: elastic-vectordb-chat
    app.kubernetes.io/name: elastic-vectordb-chat
    app.kubernetes.io/part-of: elastic-vectordb-chat-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: elastic-vectordb-chat
    weight: 100
  port:
    targetPort: 8501-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
